## NumPy (Numerical Python)

Dwi Pujining Tyas - Python for Data Science 
Hacktiv8

In [1]:
import numpy as np

### Array

Why use NumPy?
Array numpy lebih cepat dan lebih compact daripada List Python. Sebuah array megkonsumsi lebih sedikit memori dan jauh lebih convenient untuk digunakan.

In [2]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(a[0])

[1 2 3 4]


In [3]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
np.zeros(6)

#you can easily create an array filled with 0s

array([0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(6)

#or an array filled with 1s

array([1., 1., 1., 1., 1., 1.])

In [7]:
np.empty(6)

#or even an empty array!
#the function empty creates an array whose initial content is random and depends on the state of the memory

array([1., 1., 1., 1., 1., 1.])

In [13]:
#create array an array with a range of elements
print(np.arange(4))
print(np.arange(6))

print(np.arange(0,10,2)) 
#(start, stop, step)
#list np mulai dari 0 hingga 10 tetapi jangan sertakan 10 dan buat angkat tersebut melakukan kenaikan 2 setiap kali

[0 1 2 3]
[0 1 2 3 4 5]
[0 2 4 6 8]


In [16]:
np.arange(2,29,5)


array([ 2,  7, 12, 17, 22, 27])

In [17]:
np.arange(1,15,3)

array([ 1,  4,  7, 10, 13])

### Add, Remove, and Sort

In [19]:
#menambahkan elemen ke array
arr = np.array([1,2,3,4,5,6,7,8])

np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [20]:
#menghapus elemen 
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [21]:
#mengurutkan 
arr = np.array([2,1,5,3,7,4,6,8])

np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

### Shape and Size

In [22]:
array_example = np.array([[[0,1,2,3],
                          [4,5,6,7]],
                         [[0,1,2,3],
                          [4,5,6,7]],
                         [[0,1,2,3],
                          [4,5,6,7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [23]:
#mengetahui jumlah axes, atau dimensi dari array
array_example.ndim

3

In [24]:
#mengetahui jumlah total elemen array
array_example.size

24

In [25]:
#mengetahui tuple integer yang menunjuk jumlah elemen yang disimpan di sepanjang setiap dimensi array
array_example.shape

(3, 2, 4)

In [27]:
#contoh 2
arr_one = np.array([[1,2,3,4,5]])

In [28]:
arr_one.ndim

2

In [29]:
arr_one.size

5

In [30]:
arr_one.shape

(1, 5)

### Reshape

In [32]:
#akan memberikan bentuk baru ke array tanpa mengubah datanya
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [33]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [35]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

### Convert 1D to 2D

In [36]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [37]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

#akan meningkatkan dimensi array sebesar satu dimensi bila digunakan sekali

(1, 6)
[[1 2 3 4 5 6]]


In [38]:
#convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [39]:
#for a column vector, can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [40]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [41]:
# add an axis at index position 1 

b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [42]:
# add an axis at index position 0

c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

### Index and Slicing

In [43]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [44]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
# can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [46]:
five_up = (a >= 5)

print(a[five_up])
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [48]:
#select elements that are divisible by 2

divisible_by_2 = a[a%2 == 0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [49]:
#select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


### Creating Array from Existing Data

In [51]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [55]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [58]:
a_1 = np.array([[1, 1],
                [2, 2]])

a_2 = np.array([[3, 3],
                [4, 4]])

np.vstack((a_1, a_2))

#menumpuk secara vertikal

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [59]:
# stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [60]:
#membagi array yang lebih kecil
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
       [13,14,15,16,17,18,19,20,21,22,23,24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [61]:
#split menjadi 3 shaped array yang sama

np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [62]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
#membuat objek array baru yang terlihat sama dengan array asli (shallow copy) 
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [64]:
#using the copy method will make a complete copy of the array and its data (a deep copy)

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Basic array operations

In [65]:
a = np.array([1,2,3,4])
a.sum()

10

In [66]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [67]:
#sum the rows
b.sum(axis=0)

array([3, 3])

In [68]:
#sum the columns
b.sum(axis=1)

array([2, 4])

In [69]:
data = np.array([1,2])
data

array([1, 2])

In [70]:
ones = np.ones(2)
ones

array([1., 1.])

In [71]:
data + ones

array([2., 3.])

In [72]:
data * data

array([1, 4])

In [73]:
data / data

array([1., 1.])

### Broadcasting

In [75]:
data * 1.6

#mengubah informasi data ke dalam kilometer

array([1.6, 3.2])

### More Array Operations

In [77]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
             [0.54627315, 0.05093587, 0.40067661, 0.55645993],
             [0.12697682, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697682 0.82485143 0.26590556 0.56917101]]


In [78]:
A.sum()

4.8595789400000005

In [79]:
A.min()

0.05093587

In [80]:
A.min(axis=0)

array([0.12697682, 0.05093587, 0.26590556, 0.5510652 ])

In [81]:
A.max()

0.82485143

In [82]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [83]:
A.std()

0.2139211491838657

### Matrices

In [84]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.74676111 0.45909191]
 [0.66297596 0.9073889 ]
 [0.69482716 0.31846409]]


### Matrix Arithmetic

In [85]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [86]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [87]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [88]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [89]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


### Dot Product

In [91]:
#untuk menjalankan operasi dot product dengan matriks lain

a_1 = np.array([[1,2,3],[4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [92]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

### Matrix Indexing

In [94]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


### Matrix Aggregation
Menjumlahkan matriks dengan cara yang sama seperti kita menjumlahkan vektor

In [95]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [96]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [97]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


### Transposing and Reshaping

Kebutuhan untuk rotate

In [98]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [99]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [100]:
#memberikan dimensi baru

data_col = np.array([[1,2,3,4,5,6]]).T

print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [101]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [102]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [103]:
#membalikkan atau mengubah axes array sesuai dengan nilai yang kalian tentukan

arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


### N - Dimensional Array

In [105]:
ndarr = np.array([[[1,2], [3,4]],
                 [[5,6], [7,8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [106]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [107]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [108]:
print(np.random.random((4,3,2)))

[[[0.17110775 0.3846855 ]
  [0.09717373 0.72693911]
  [0.93284627 0.96262071]]

 [[0.6598119  0.12856832]
  [0.88305779 0.37603453]
  [0.16490995 0.90205576]]

 [[0.66667271 0.89282051]
  [0.73230332 0.76639097]
  [0.29778191 0.40504347]]

 [[0.46490022 0.24372801]
  [0.22833238 0.3558677 ]
  [0.2446901  0.00478378]]]


### Flatten N-Dimensional Array

Ada dua cara populer untuk meratakan array

In [109]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [110]:
#use flatten to flatten your array into a 1D array
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### Working with Math Formulas

Mengimpelmentasikan rumus matematika yang bekerja pada array

In [111]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined

### TipsPy

Notes on Numpy Vector

In [112]:
a = np.random.rand(5)
print(a)

[0.70453819 0.39289206 0.44658658 0.79812532 0.45217573]


In [113]:
a.shape #rank 1 array

(5,)

In [114]:
#melakukan operasi rank transpose terhadap rank 1 array
print(a.T)

[0.70453819 0.39289206 0.44658658 0.79812532 0.45217573]


In [115]:
#operasi dot produk pada Rank 1 Array

print(np.dot(a, a.T))

1.6916447146511966


Operasi yang dilakukan tidak menunjukkan hasil yang seharusnya. Karena Rank 1 Array hanya mempunyai baris atau kolom saja

Tips untuk membuat array adalah selalu masukan 2 argumen ketika akan membuat column ataupun row Vector.

In [116]:
a = np.random.rand(5,1) #column vector

print(a)

[[0.53709721]
 [0.9000963 ]
 [0.93073942]
 [0.06050123]
 [0.3678773 ]]


In [117]:
print(a.T)

[[0.53709721 0.9000963  0.93073942 0.06050123 0.3678773 ]]


In [118]:
print(np.dot(a, a.T))

[[0.28847342 0.48343921 0.49989755 0.03249504 0.19758587]
 [0.48343921 0.81017334 0.83775511 0.05445693 0.331125  ]
 [0.49989755 0.83775511 0.86627588 0.05631088 0.34239791]
 [0.03249504 0.05445693 0.05631088 0.0036604  0.02225703]
 [0.19758587 0.331125   0.34239791 0.02225703 0.13533371]]


In [120]:
#row vector
a = np.random.rand(1,5)

print(a)

[[0.2310968  0.20961451 0.03312272 0.55555994 0.91280795]]


Don't use rank 1 Array; Always use 1 by n matrices or n by 1 matrices instead. (column or row vectors)